// Define windows width and height
#define WINDOWS_WIDTH 1000
#define WINDOWS_HEIGHT 700
#define WINDOWS_FULL_WIDTH glutGet(GLUT_SCREEN_WIDTH)
#define WINDOWS_FULL_HEIGHT glutGet(GLUT_SCREEN_HEIGHT)
#define WINDOWS_CENTER_X WINDOWS_FULL_WIDTH / 2
#define WINDOWS_CENTER_Y WINDOWS_FULL_HEIGHT / 2

#define WATCH_BODY_RADIUS 150

#define COMPLICATION_RING_RADIUS 100